import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import Footer from "@/components/Footer";
import { ModalProvider } from "@/context/ModalContext";
import Script from "next/script"; // ✅ import Script from next/script

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Forgestack",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* ✅ Add Google Analytics scripts here */}
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-4FWWS7EXT3"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-4FWWS7EXT3');
          `}
        </Script>

        <ModalProvider>
          {children}
          <Footer />
        </ModalProvider>
      </body>
    </html>
  );
}
